require: rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "db/**/*"
    - "lib/**/*"
    - "config/**/*"
    - "Gemfile"
    - "Rakefile"
    - "bin/**"
    - "app/views/**/*"

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to a set number of characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Enabled: true
  Max: 180

Metrics/ParameterLists:
  Description: 'Avoid parameter lists longer than three or four parameters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#too-many-params'
  Enabled: true
  Max: 3
